name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: '0.147.9'
      HUGO_ENVIRONMENT: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: static/slides-deck/package-lock.json

      - name: Install VitePress dependencies
        run: npm ci
        working-directory: static/slides-deck

      - name: Build VitePress
        run: npm run build
        working-directory: static/slides-deck

      - name: Copy VitePress build to Hugo static
        run: |
          mkdir -p static/slides-deck
          cp -r static/slides-deck/.vitepress/dist/* static/slides-deck/

      - name: Setup Hugo
        run: |
          wget -O $RUNNER_TEMP/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i $RUNNER_TEMP/hugo.deb

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Generate icons JSON
        run: |
          find static/img/icons -type f -name '*.svg' | awk -F '/' '{
            name = $NF; sub(/\.svg$/, "", name);
            print "{\"name\": \"" name "\", \"path\": \"/img/icons/" $NF "\"},"
          }' | sed '$ s/,$//' | awk 'BEGIN {print "["} {print} END {print "]"}' > static/img/icons/icons.json

      - name: Build with Hugo
        run: |
          hugo --gc --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
